export const MIN_PROFIT = 2000;
export const MIN_PROFIT_RATIO = 0.5;

export const MIN_PROFIT_TO_QUICK_BUY = 10000;
export const MIN_PROFIT_RATIO_TO_QUICK_BUY = 0.4;

export const ASSUMED_PRICE_IF_JELLYNEO_DOESNT_KNOW = 10000;

export const MAX_COPIES_TO_SHELVE = 2;
export const MAX_COPIES_TO_SHELVE_IF_VALUABLE = 5;

export const MAX_DROUGHT_CYCLES_UNTIL_GIVING_UP = 1;
export const TIME_BETWEEN_REFRESHES = 7777;
export const TIME_BETWEEN_RESTOCK_CYCLES = 66666;

export const DAYS_BEFORE_REPRICING_SHOP_STOCK = 1;

export const TIME_TO_CHOOSE_ITEM = 1111;
export const TIME_TO_MAKE_HAGGLE_OFFER = 888;
